import { describe, expect, it } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import { LandingPage } from '../src/components/landing-page';

describe('LandingPage', () => {
  it('leads with the product outcome and a three-command CLI success path', () => {
    const html = renderToStaticMarkup(<LandingPage onNavigate={() => {}} />);

    expect(html).toContain('LPC Toolkit');
    expect(html).toContain('Create attributed LPC characters');
    expect(html).toContain('Farmer character preview generated by LPC Toolkit');
    expect(html).toContain('hero.preview.png');
    expect(html).toContain('hero.credits.txt');
    expect(html).toContain('hero.credits.csv');

    expect(html.match(/Open Composer/g)).toHaveLength(1);
    expect(html).not.toContain('Repair an Asset Pack');
    expect(html).toContain('href="#cli-quick-start"');
    expect(html).toContain('Use the CLI');
    expect(html).toContain('id="cli-quick-start"');

    const quickStartCommands = [
      'npm install -g @lpc-toolkit/cli',
      'lpc-toolkit character create hero --preset farmer',
      'lpc-toolkit character preview hero',
    ];
    const quickStartPositions = quickStartCommands.map((command) => {
      expect(html).toContain(command);
      return html.indexOf(command);
    });
    expect(quickStartPositions).toEqual(
      [...quickStartPositions].sort((left, right) => left - right),
    );

    expect(html).toContain('npx @lpc-toolkit/cli --help');
    expect(html).toContain('Node.js 22 or newer');
    expect(html).toContain('about 205 MB');
    expect(html).toContain('id="codex-plugin"');
    expect(html).toContain('Install the Codex plugin');
    expect(html).toContain(
      'codex plugin marketplace add ochowei/lpc-toolkit-2026-1',
    );
    expect(html).toContain('codex plugin add lpc-toolkit@lpc-toolkit');
    expect(html).toContain('https://github.com/ochowei/lpc-toolkit-2026-1#codex-plugin');
    expect(html).toContain('whitespace-normal break-words');
    expect(html).not.toContain('overflow-x-auto');
    expect(html).toContain('characters/previews/hero/');
    expect(html).toContain('hero.metadata.json');
    expect(html).toContain('Keep both credit files with the generated sprite.');

    const customizationCommands = [
      'lpc-toolkit character search hero --type hair --query braid',
      'lpc-toolkit catalog item hair_braid',
      'lpc-toolkit character set hero --type hair --item hair_braid --recolor lpcr.brown',
      'lpc-toolkit character set-color hero --type expression --channel eyes --color green',
      'lpc-toolkit character render hero --out ./dist/hero --animation walk --bundle zip',
    ];
    for (const command of customizationCommands) expect(html).toContain(command);

    expect(html).toContain('.viewer.html');
    expect(html).toContain('offline');

    expect(html).toContain(
      'https://github.com/ochowei/lpc-toolkit-2026-1/blob/main/packages/cli/README.md',
    );
    expect(html).not.toContain('page.nextOffset');
    expect(html).not.toContain('lpc-toolkit selection validate');
    expect(html).not.toContain('lpc-toolkit token encode');
  });

  it('documents the public CLI artist workflow without requiring a repository clone', () => {
    const html = renderToStaticMarkup(<LandingPage onNavigate={() => {}} />)
      .replaceAll('&quot;', '"')
      .replaceAll('&lt;', '<')
      .replaceAll('&gt;', '>');
    const commands = [
      'npm install -g @lpc-toolkit/cli',
      'lpc-toolkit asset workspace init ./my-lpc-art',
      'cd ./my-lpc-art',
      'lpc-toolkit asset init --new --pack-id acme.fantasy-hair --asset-id moon-braid --display-name "Moon Braid" --type hair --body-type male --body-type female --animation walk --animation climb --author Alice --license "CC-BY-SA 4.0" --url https://example.com/acme/fantasy-hair',
      'lpc-toolkit asset validate ./artist-packs/<pack-id>',
      'lpc-toolkit asset preview ./artist-packs/<pack-id>',
      'lpc-toolkit asset sync ./artist-packs/<pack-id>',
      'lpc-toolkit asset pack ./artist-packs/<pack-id>',
      'lpc-toolkit asset workspace init ../consumer-workspace',
      'cd ../consumer-workspace',
      'lpc-toolkit asset install ../my-lpc-art/artist-packs/<pack-id>-<version>.lpc-assets.zip',
      'lpc-toolkit asset doctor',
    ];
    const positions = commands.map((command) => {
      expect(html).toContain(command);
      return html.indexOf(command);
    });

    expect(positions).toEqual([...positions].sort((left, right) => left - right));
    expect(html).toContain('artist-packs/<pack-id>/sprites/');
    expect(html).toContain('You do not need to clone this repository');
    expect(html).not.toContain('Phase 3');
    expect(html).toContain('browser can inspect, validate, repair, and assemble');
    expect(html).toContain('CLI owns package inspection, install, upgrade, removal, and lifecycle diagnosis');
    expect(html).toContain('Web edits happen in-memory');
    expect(html).toContain('status: "draft"');
    expect(html).toContain('CLI refuses to install them');
  });
});
