/**
 * Enumerates the catalog-derived picker strings that need Traditional
 * Chinese translations, and (re)generates packages/web/src/i18n-item-names.ts.
 *
 * Reads the read-only upstream/ submodule; upstream/ is never written.
 * Re-running is merge-safe: existing translations are preserved and any new
 * asset names are appended with an identity value, so this also serves as a
 * maintenance check when upstream adds assets.
 *
 * Run: pnpm --filter @lpc-toolkit/web exec tsx scripts/gen-i18n-data.ts
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  createCatalog,
  type FilePath,
  type ItemDefinition,
} from '@lpc-toolkit/core';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../../..');
const sheetDefsDir = path.join(repoRoot, 'upstream/sheet_definitions');
const outFile = path.join(here, '../src/i18n-item-names.ts');

if (!existsSync(sheetDefsDir)) {
  console.error(
    '[gen-i18n] upstream/ not initialized. Run: git submodule update --init',
  );
  process.exit(1);
}

function walkJson(dir: string, base = dir): Record<FilePath, ItemDefinition> {
  const out: Record<FilePath, ItemDefinition> = {};
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) Object.assign(out, walkJson(full, base));
    else if (entry.name.endsWith('.json')) {
      const key = path.relative(base, full).split(path.sep).join('/');
      out[key] = JSON.parse(readFileSync(full, 'utf8')) as ItemDefinition;
    }
  }
  return out;
}

const { catalog } = createCatalog(walkJson(sheetDefsDir));

const names = new Set<string>();
const categories = new Set<string>();
for (const item of catalog.byItemId.values()) {
  names.add(item.name);
  categories.add(item.type_name);
  // sourcePath is the sheet_definitions-relative file path; its directory
  // segments mirror the advanced-tree folder headers, so collect them too.
  const parts = (item.sourcePath ?? '').split('/').filter(Boolean);
  for (const seg of parts.slice(0, -1)) categories.add(seg);
}

// Preserve translations produced by a previous run.
const existing: Record<string, string> = {};
if (existsSync(outFile)) {
  const mod = await import(pathToFileURL(outFile).href);
  Object.assign(existing, mod.ITEM_NAME_LABELS_ZH ?? {});
}

const sortedNames = [...names].sort((a, b) => a.localeCompare(b, 'en'));
const body = sortedNames
  .map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(existing[n] ?? n)},`)
  .join('\n');

writeFileSync(
  outFile,
  '// AUTO-GENERATED by scripts/gen-i18n-data.ts.\n' +
    '// Values are hand-translated; re-running preserves existing translations.\n' +
    'export const ITEM_NAME_LABELS_ZH: Record<string, string> = {\n' +
    `${body}\n};\n`,
);

const untranslated = sortedNames.filter((n) => (existing[n] ?? n) === n);
console.log(
  `asset names: ${sortedNames.length} (untranslated: ${untranslated.length})`,
);
console.log(`-> wrote ${path.relative(repoRoot, outFile)}`);
console.log(`\n# CATEGORY LABELS (${categories.size}) — translate in i18n.ts:`);
for (const c of [...categories].sort((a, b) => a.localeCompare(b, 'en'))) {
  console.log(c);
}
