import {
  ANIMATION_CONFIGS,
  composeSelections,
  extractAnimation,
  makeResolvePalette,
  DIRECTIONS,
  type CanvasAdapter,
  type Catalog,
  type PaletteMetadata,
  type ItemDefinition,
  type Direction,
} from '@lpc-toolkit/core';
import { buildItemThumbnailSelections } from '../src/lib/item-thumbnail-selection';
import { frameRect } from '../src/slice/frame-rect';
import {
  findAlphaBounds,
  MAX_AUTO_FRAME_SCALE,
  MIN_AUTO_FRAME_SCALE,
  MIN_THUMBNAIL_SIZE,
  THUMBNAIL_MARGIN,
  type AlphaBounds,
} from '../src/lib/thumbnail-framing';

export type { AlphaBounds } from '../src/lib/thumbnail-framing';
export { findAlphaBounds } from '../src/lib/thumbnail-framing';

export interface ThumbnailMetrics {
  readonly widthRatio: number;
  readonly heightRatio: number;
  readonly visibleWidthAt24: number;
  readonly visibleHeightAt24: number;
  readonly fitScalePxPerSourcePixel: number;
  readonly additionalScaleOverCurrent: number;
}

export interface ThumbnailAuditRow {
  readonly itemId: string;
  readonly typeName: string;
  readonly itemName: string;
  readonly bodyType: string;
  readonly variant?: string;
  readonly animation?: string;
  readonly direction?: string;
  readonly frameIndex?: number;
  readonly frameSize?: number;
  readonly status: 'ok' | 'empty' | 'error';
  readonly bounds?: AlphaBounds;
  readonly metrics?: ThumbnailMetrics;
  readonly missingPaths?: readonly string[];
  readonly errorMessage?: string;
}

export interface AuditCase {
  readonly itemId: string;
  readonly item: ItemDefinition;
  readonly bodyType: string;
  readonly variant?: string;
}

export type ThumbnailBoundsOverrides = Readonly<Record<string, AlphaBounds>>;

export const AUDIT_BODY_TYPES = ['male', 'female'] as const;

export function deriveThumbnailMetrics(
  bounds: AlphaBounds,
  frameSize: number,
): ThumbnailMetrics {
  const currentScale = 24 / frameSize;
  const fitScalePxPerSourcePixel = Math.min(
    20 / bounds.width,
    20 / bounds.height,
  );
  return {
    widthRatio: bounds.width / frameSize,
    heightRatio: bounds.height / frameSize,
    visibleWidthAt24: bounds.width * currentScale,
    visibleHeightAt24: bounds.height * currentScale,
    fitScalePxPerSourcePixel,
    additionalScaleOverCurrent: fitScalePxPerSourcePixel / currentScale,
  };
}

function auditCaseKey(row: ThumbnailAuditRow): string {
  return `${row.itemId}|${row.bodyType}|${row.variant ?? '_'}`;
}

export function applyThumbnailBoundsOverrides(
  rows: readonly ThumbnailAuditRow[],
  overrides: ThumbnailBoundsOverrides,
): readonly ThumbnailAuditRow[] {
  return rows.map((row) => {
    const bounds = overrides[auditCaseKey(row)];
    return bounds && row.status === 'ok' && row.frameSize
      ? {
          ...row,
          bounds,
          metrics: deriveThumbnailMetrics(bounds, row.frameSize),
        }
      : row;
  });
}

function median(values: readonly number[]): number {
  const sorted = [...values].sort((a, b) => a - b);
  const middle = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? ((sorted[middle - 1] ?? 0) + (sorted[middle] ?? 0)) / 2
    : (sorted[middle] ?? 0);
}

function roundScale(value: number): number {
  return Number(value.toFixed(6));
}

export function deriveThumbnailTypeScales(
  rows: readonly ThumbnailAuditRow[],
): Readonly<Record<string, number>> {
  const byType = new Map<string, ThumbnailAuditRow[]>();
  for (const row of rows) {
    if (row.status !== 'ok' || !row.bounds || !row.metrics || !row.frameSize) {
      continue;
    }
    const group = byType.get(row.typeName) ?? [];
    group.push(row);
    byType.set(row.typeName, group);
  }

  const result: Record<string, number> = {};
  for (const typeName of [...byType.keys()].sort()) {
    const group = byType.get(typeName) ?? [];
    const targetScale = median(
      group.map((row) => row.metrics?.additionalScaleOverCurrent ?? 0),
    );
    const innerSize = MIN_THUMBNAIL_SIZE - THUMBNAIL_MARGIN * 2;
    const safeScale = Math.min(...group.map((row) => {
      const bounds = row.bounds;
      const frameSize = row.frameSize;
      if (!bounds || !frameSize) return 0;
      return Math.min(
        innerSize * frameSize / (MIN_THUMBNAIL_SIZE * bounds.width),
        innerSize * frameSize / (MIN_THUMBNAIL_SIZE * bounds.height),
      );
    }));
    const scale = roundScale(
      Math.min(targetScale, safeScale, MAX_AUTO_FRAME_SCALE),
    );
    if (scale >= MIN_AUTO_FRAME_SCALE) result[typeName] = scale;
  }
  return result;
}

export function serializeThumbnailFramingPolicy(
  scales: Readonly<Record<string, number>>,
): string {
  const entries = Object.entries(scales).sort(([a], [b]) =>
    a.localeCompare(b),
  );
  const body = entries
    .map(([typeName, scale]) => `  ${JSON.stringify(typeName)}: ${scale},`)
    .join('\n');
  const version = `v1:${entries
    .map(([typeName, scale]) => `${typeName}=${scale}`)
    .join(',')}`;
  return [
    '// AUTO-GENERATED by scripts/audit-thumbnail-visible-bounds.ts.',
    '// Do not edit by hand. Regenerate with pnpm audit:thumbnail-bounds.',
    '',
    `export const THUMBNAIL_FRAMING_POLICY_VERSION = ${JSON.stringify(version)};`,
    '',
    'export const THUMBNAIL_TYPE_SCALES = {',
    body,
    '} as const;',
    '',
  ].join('\n');
}

export function expandAuditCases(
  catalog: Catalog,
  bodyTypes: readonly string[],
): readonly AuditCase[] {
  const cases: AuditCase[] = [];
  const itemEntries = Array.from(catalog.byItemId.entries()).sort((a, b) =>
    a[0].localeCompare(b[0]),
  );

  for (const [itemId, item] of itemEntries) {
    for (const bodyType of bodyTypes) {
      // Check compatibility
      const bodyTypesObj = (item as any).body_types;
      if (bodyTypesObj) {
        if (!bodyTypesObj[bodyType]) {
          continue;
        }
      } else {
        // Fallback: check if any layer_N has this bodyType, if layers exist
        let hasLayers = false;
        let hasBodyTypeInLayers = false;
        for (const key of Object.keys(item)) {
          if (key.startsWith('layer_')) {
            hasLayers = true;
            const layer = (item as any)[key];
            if (layer && typeof layer === 'object' && layer[bodyType] !== undefined) {
              hasBodyTypeInLayers = true;
            }
          }
        }
        if (hasLayers && !hasBodyTypeInLayers) {
          continue;
        }
      }

      // Handle variants
      const variants = item.variants;
      if (variants && variants.length > 0) {
        for (const variant of variants) {
          cases.push({
            itemId,
            item,
            bodyType,
            variant,
          });
        }
      } else {
        cases.push({
          itemId,
          item,
          bodyType,
        });
      }
    }
  }

  return cases;
}

export function rowsToCsv(rows: readonly ThumbnailAuditRow[]): string {
  const columns = [
    'itemId',
    'typeName',
    'itemName',
    'bodyType',
    'variant',
    'animation',
    'direction',
    'frameIndex',
    'frameSize',
    'status',
    'boundsX',
    'boundsY',
    'boundsWidth',
    'boundsHeight',
    'widthRatio',
    'heightRatio',
    'visibleWidthAt24',
    'visibleHeightAt24',
    'fitScalePxPerSourcePixel',
    'additionalScaleOverCurrent',
    'missingPaths',
    'errorMessage',
  ];

  const headerRow = columns.join(',');
  const dataRows = rows.map(row => {
    return columns
      .map(col => {
        let val: any = '';
        if (col === 'boundsX') val = row.bounds?.x;
        else if (col === 'boundsY') val = row.bounds?.y;
        else if (col === 'boundsWidth') val = row.bounds?.width;
        else if (col === 'boundsHeight') val = row.bounds?.height;
        else if (col === 'widthRatio') val = row.metrics?.widthRatio;
        else if (col === 'heightRatio') val = row.metrics?.heightRatio;
        else if (col === 'visibleWidthAt24') val = row.metrics?.visibleWidthAt24;
        else if (col === 'visibleHeightAt24') val = row.metrics?.visibleHeightAt24;
        else if (col === 'fitScalePxPerSourcePixel') val = row.metrics?.fitScalePxPerSourcePixel;
        else if (col === 'additionalScaleOverCurrent') val = row.metrics?.additionalScaleOverCurrent;
        else if (col === 'missingPaths') val = row.missingPaths?.join('; ');
        else {
          val = (row as any)[col];
        }

        if (val === undefined || val === null) {
          return '';
        }
        const str = String(val);
        return `"${str.replace(/"/g, '""')}"`;
      })
      .join(',');
  });

  return [headerRow, ...dataRows].join('\n') + '\n';
}

export function percentile(values: readonly number[], p: number): number {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const len = sorted.length;
  if (len === 1) return sorted[0] ?? 0;
  const idx = (len - 1) * (p / 100);
  const low = Math.floor(idx);
  const high = Math.ceil(idx);
  const valLow = sorted[low];
  const valHigh = sorted[high];
  if (valLow === undefined || valHigh === undefined) return 0;
  if (low === high) return valLow;
  return valLow + (idx - low) * (valHigh - valLow);
}

function compareCases(a: ThumbnailAuditRow, b: ThumbnailAuditRow): number {
  const itemIdComp = a.itemId.localeCompare(b.itemId);
  if (itemIdComp !== 0) return itemIdComp;
  const btComp = a.bodyType.localeCompare(b.bodyType);
  if (btComp !== 0) return btComp;
  const varComp = (a.variant || '').localeCompare(b.variant || '');
  if (varComp !== 0) return varComp;
  const animComp = (a.animation || '').localeCompare(b.animation || '');
  if (animComp !== 0) return animComp;
  const dirComp = (a.direction || '').localeCompare(b.direction || '');
  if (dirComp !== 0) return dirComp;
  return (a.frameIndex || 0) - (b.frameIndex || 0);
}

const sortByWidthAsc = (a: ThumbnailAuditRow, b: ThumbnailAuditRow) => {
  const wA = a.bounds?.width ?? 0;
  const wB = b.bounds?.width ?? 0;
  if (wA !== wB) return wA - wB;
  return compareCases(a, b);
};

const sortByHeightAsc = (a: ThumbnailAuditRow, b: ThumbnailAuditRow) => {
  const hA = a.bounds?.height ?? 0;
  const hB = b.bounds?.height ?? 0;
  if (hA !== hB) return hA - hB;
  return compareCases(a, b);
};

const sortByWidthDesc = (a: ThumbnailAuditRow, b: ThumbnailAuditRow) => {
  const wA = a.bounds?.width ?? 0;
  const wB = b.bounds?.width ?? 0;
  if (wA !== wB) return wB - wA;
  return compareCases(a, b);
};

const sortByHeightDesc = (a: ThumbnailAuditRow, b: ThumbnailAuditRow) => {
  const hA = a.bounds?.height ?? 0;
  const hB = b.bounds?.height ?? 0;
  if (hA !== hB) return hB - hA;
  return compareCases(a, b);
};

export function summaryToMarkdown(rows: readonly ThumbnailAuditRow[]): string {
  const lines: string[] = [];
  lines.push('# Thumbnail Visible Bounds Audit');
  lines.push('');

  // 1. Overall Status Counts
  const statusCounts = { ok: 0, empty: 0, error: 0 };
  for (const row of rows) {
    statusCounts[row.status] = (statusCounts[row.status] || 0) + 1;
  }

  lines.push('## Status Summary');
  lines.push('');
  lines.push('| Status | Count |');
  lines.push('| --- | --- |');
  lines.push(`| ok | ${statusCounts.ok} |`);
  lines.push(`| empty | ${statusCounts.empty} |`);
  lines.push(`| error | ${statusCounts.error} |`);
  lines.push('');

  // 2. Group by Type Name
  lines.push('## By Type');
  lines.push('');

  const typeNames = Array.from(new Set(rows.map(r => r.typeName))).sort();

  for (const typeName of typeNames) {
    const typeRows = rows.filter(r => r.typeName === typeName);
    const typeOkRows = typeRows.filter(r => r.status === 'ok');
    const typeStatusCounts = { ok: 0, empty: 0, error: 0 };
    for (const r of typeRows) {
      typeStatusCounts[r.status] = (typeStatusCounts[r.status] || 0) + 1;
    }

    lines.push(`### Type: ${typeName}`);
    lines.push('');
    lines.push(`- Total cases: ${typeRows.length}`);
    lines.push(`- Statuses: ok: ${typeStatusCounts.ok}, empty: ${typeStatusCounts.empty}, error: ${typeStatusCounts.error}`);
    lines.push('');

    if (typeOkRows.length > 0) {
      const widths = typeOkRows.map(r => r.metrics?.visibleWidthAt24 ?? 0);
      const heights = typeOkRows.map(r => r.metrics?.visibleHeightAt24 ?? 0);
      const fitScales = typeOkRows.map(r => r.metrics?.fitScalePxPerSourcePixel ?? 0);
      const additionalScales = typeOkRows.map(r => r.metrics?.additionalScaleOverCurrent ?? 0);

      lines.push('| Metric (Visible at 24px) | Min | P50 (Median) | P90 | P95 | Max |');
      lines.push('| --- | --- | --- | --- | --- | --- |');
      lines.push(`| Width | ${percentile(widths, 0).toFixed(2)} | ${percentile(widths, 50).toFixed(2)} | ${percentile(widths, 90).toFixed(2)} | ${percentile(widths, 95).toFixed(2)} | ${percentile(widths, 100).toFixed(2)} |`);
      lines.push(`| Height | ${percentile(heights, 0).toFixed(2)} | ${percentile(heights, 50).toFixed(2)} | ${percentile(heights, 90).toFixed(2)} | ${percentile(heights, 95).toFixed(2)} | ${percentile(heights, 100).toFixed(2)} |`);
      lines.push(`| Fit Scale | ${percentile(fitScales, 0).toFixed(2)} | ${percentile(fitScales, 50).toFixed(2)} | ${percentile(fitScales, 90).toFixed(2)} | ${percentile(fitScales, 95).toFixed(2)} | ${percentile(fitScales, 100).toFixed(2)} |`);
      lines.push(`| Additional Scale | ${percentile(additionalScales, 0).toFixed(2)} | ${percentile(additionalScales, 50).toFixed(2)} | ${percentile(additionalScales, 90).toFixed(2)} | ${percentile(additionalScales, 95).toFixed(2)} | ${percentile(additionalScales, 100).toFixed(2)} |`);
      lines.push('');
    } else {
      lines.push('*No successful cases to calculate metrics.*');
      lines.push('');
    }
  }

  // 3. Smallest and Largest Successful Cases
  const okRows = rows.filter(r => r.status === 'ok');

  lines.push('## Bounds Extremes');
  lines.push('');

  const renderExtremesTable = (title: string, sortedRows: ThumbnailAuditRow[]) => {
    lines.push(`### ${title}`);
    lines.push('');
    lines.push('| Item ID | Body | Variant | Anim/Dir/Frame | Bounds (W x H) | Visible Size (24px) | Fit Scale |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- |');
    for (const r of sortedRows.slice(0, 10)) {
      const animInfo = `${r.animation ?? '-'}/${r.direction ?? '-'}/${r.frameIndex ?? 0}`;
      const boundsStr = r.bounds ? `${r.bounds.width}x${r.bounds.height}` : '-';
      const visibleSizeStr = r.metrics ? `${r.metrics.visibleWidthAt24.toFixed(2)}x${r.metrics.visibleHeightAt24.toFixed(2)}` : '-';
      const fitScaleStr = r.metrics?.fitScalePxPerSourcePixel.toFixed(2) ?? '-';
      lines.push(`| \`${r.itemId}\` | ${r.bodyType} | ${r.variant ?? '-'} | ${animInfo} | ${boundsStr} | ${visibleSizeStr} | ${fitScaleStr} |`);
    }
    lines.push('');
  };

  if (okRows.length > 0) {
    const smallestByWidth = [...okRows].sort(sortByWidthAsc);
    const smallestByHeight = [...okRows].sort(sortByHeightAsc);
    const largestByWidth = [...okRows].sort(sortByWidthDesc);
    const largestByHeight = [...okRows].sort(sortByHeightDesc);

    renderExtremesTable('Top 10 Smallest Cases by Width', smallestByWidth);
    renderExtremesTable('Top 10 Smallest Cases by Height', smallestByHeight);
    renderExtremesTable('Top 10 Largest Cases by Width', largestByWidth);
    renderExtremesTable('Top 10 Largest Cases by Height', largestByHeight);
  } else {
    lines.push('*No successful cases to report extremes.*');
    lines.push('');
  }

  // 4. Empty and Error Cases
  const errorOrEmptyRows = rows.filter(r => r.status === 'empty' || r.status === 'error' || (r.missingPaths && r.missingPaths.length > 0));
  const sortedErrorOrEmptyRows = [...errorOrEmptyRows].sort(compareCases);

  lines.push('## Empty, Error, or Missing Path Cases');
  lines.push('');
  if (sortedErrorOrEmptyRows.length > 0) {
    lines.push('| Item ID | Body | Variant | Status | Missing Paths / Error Message |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const r of sortedErrorOrEmptyRows) {
      let detail = '';
      if (r.missingPaths && r.missingPaths.length > 0) {
        detail = `Missing: ${r.missingPaths.join(', ')}`;
      }
      if (r.errorMessage) {
        if (detail) detail += '; ';
        detail += r.errorMessage;
      }
      lines.push(`| \`${r.itemId}\` | ${r.bodyType} | ${r.variant ?? '-'} | ${r.status} | ${detail || '-'} |`);
    }
    lines.push('');
  } else {
    lines.push('*No empty, error, or missing path cases found.*');
    lines.push('');
  }

  return lines.join('\n');
}

export interface RunAuditCaseDeps {
  readonly catalog: Catalog;
  readonly palettes: PaletteMetadata;
  readonly adapter: CanvasAdapter;
  readonly failedPaths: readonly string[];
}

export async function runAuditCase(
  auditCase: AuditCase,
  deps: RunAuditCaseDeps,
): Promise<ThumbnailAuditRow> {
  const base = {
    itemId: auditCase.itemId,
    typeName: auditCase.item.type_name,
    itemName: auditCase.item.name,
    bodyType: auditCase.bodyType,
    ...(auditCase.variant !== undefined ? { variant: auditCase.variant } : {}),
    direction: 'down' as const,
    frameIndex: 0,
  };

  try {
    const selections = buildItemThumbnailSelections({
      item: auditCase.item,
      bodyType: auditCase.bodyType,
      ...(auditCase.variant !== undefined ? { variant: auditCase.variant } : {}),
    });
    const sheet = await composeSelections(selections, {
      catalog: deps.catalog,
      adapter: deps.adapter,
      spritesheetsBaseUrl: '',
      resolvePalette: makeResolvePalette(deps.catalog, deps.palettes, selections),
    });

    let animationName: string | undefined =
      sheet.animations.includes('walk') ? 'walk' : sheet.animations[0];
    let customRegion = null;

    if (!animationName && sheet.customAnimations && sheet.customAnimations.size > 0) {
      animationName = Array.from(sheet.customAnimations.keys())[0];
      customRegion = sheet.customAnimations.get(animationName!);
    }

    if (!animationName) {
      return { ...base, status: 'error', missingPaths: [...deps.failedPaths], errorMessage: 'No composed animation' };
    }

    const animation = extractAnimation(sheet, animationName, { adapter: deps.adapter });

    // Direction fallback loop
    const directionsToTry: Direction[] = ['down', 'up', 'left', 'right'];
    let bounds: AlphaBounds | null = null;
    let finalDirection: Direction = 'down';
    let frameSize = 64;

    if (customRegion) {
      frameSize = customRegion.frameSize;
      for (const dir of directionsToTry) {
        const dirIndex = DIRECTIONS.indexOf(dir);
        if (dirIndex >= 0 && dirIndex < customRegion.rows) {
          const sx = 0;
          const sy = dirIndex * frameSize;
          const pixels = animation.canvas.getContext('2d')
            .getImageData(sx, sy, frameSize, frameSize);
          bounds = findAlphaBounds(pixels.data, frameSize, frameSize);
          if (bounds) {
            finalDirection = dir;
            break;
          }
        }
      }
    } else {
      const config = ANIMATION_CONFIGS[animation.animation];
      if (!config) {
        return { ...base, animation: animationName, status: 'error', missingPaths: [...deps.failedPaths], errorMessage: 'Representative animation has no standard frame config' };
      }
      frameSize = 64;
      for (const dir of directionsToTry) {
        const rect = frameRect(config, animation.directions, dir, 0);
        const pixels = animation.canvas.getContext('2d')
          .getImageData(rect.sx, rect.sy, rect.size, rect.size);
        bounds = findAlphaBounds(pixels.data, rect.size, rect.size);
        if (bounds) {
          finalDirection = dir;
          break;
        }
      }
    }

    if (!bounds) {
      return {
        ...base,
        animation: animationName,
        frameSize,
        status: 'empty',
        missingPaths: [...deps.failedPaths]
      };
    }

    return {
      ...base,
      animation: animationName,
      direction: finalDirection,
      frameSize,
      status: 'ok',
      bounds,
      metrics: deriveThumbnailMetrics(bounds, frameSize),
      missingPaths: [...deps.failedPaths],
    };
  } catch (error) {
    return {
      ...base,
      status: 'error',
      missingPaths: [...deps.failedPaths],
      errorMessage: error instanceof Error ? error.message : String(error),
    };
  }
}

